### PR TITLE
Pegasus

### PR DESCRIPTION
**Pull request by AbdealiLoKo**

### CODE REVIEW

**Comment by AbdealiLoKo** [comment]
@kunalgrover05 please use `git push -f` on the branch (not on master) and clean up the commits.

Lots of things are written in one and removed in another commits and commits are too long - not very easy to read

**Comment by kunalgrover05** [comment]
Is this fine? Should be easy to read now.

**Comment by AbdealiLoKo** [comment]
It's still pretty big ...

**Comment by kunalgrover05** [comment]
Come on, work with this for now. Will take care from next time.

http://about.me/kunalgrover05

_Kunal Grover_
III Year Undergraduate
http://about.me/kunalgrover05
Department of Mechanical Engineering
Indian Institute of Technology Madras
about.me/kunalgrover05
http://about.me/kunalgrover05
http://about.me/kunalgrover05

**Pull request merged**
