### PR TITLE
Pegasus policy fix

### PR DESCRIPTION
**Pull request by kunalgrover05**
The gradient method in master seems to always diverge. Not sure why. Bugs found in that: value wasnt updated to 0 after last_action.
The 3 point gradient method in this branch converges, the only reason it wasn't converging was since it was trying to minimize instead of maximizing. 
Also modified the state to be delta(z) since it makes more sense with this linear policy class, as output of 
vel = A(del(z)) + b is more meaningful as for a certain desired state z0, if we move down and we move up, the variation is much better than if we use A(z)+b

### CODE REVIEW

**Comment by AbdealiLoKo** [comment]
del(z) is basically the velocity ... so, can't you just do `a \* z + b \* vz
- c` to be more nice ?

**Comment by AbdealiLoKo** [comment]
Ah - you meant del = target - actual.

Yeah, that makes much more sense.

**Comment by AbdealiLoKo** [comment]
I rebased on master and pushed as it had conflicts with master

**Comment by AbdealiLoKo** [comment]
Hey, also - wanted to mention a few things:
1. I've done some templated thing (in `core.hh`) to override the `<<` operator. So, `print_vector` is not needed anymore ... just do `std::cout << vector1` and it will print like `[1.5, 2.2, 3.0]`
2. Youre calculating the gradient as `gradient = (right_value - left_value)` should it not be `gradient = (right_value - left_value) / epsilon`
3. When updating the next param in `!left_done` you use alpha : `policy[parameter] = old_policy[parameter] - alpha;` but in left you use `policy[parameter] = old_policy[parameter] + epsilon;`
   Souldnt you use `epsilon` for both cases ? One should be `-epsilon`, other should be `2*epsilon`

It seems to converge for me too :) Finally we have reproducable results !
I notice that it converges slowly though - very slowly

**Comment by kunalgrover05** [comment]
1. Cool
2. Not needed, since we are multiplying by alpha, we can change it for observations.
   I observed blowing up due to small epsilon which will either cause the agent to not converge or take more time to converge if alpha is wrong.
3. Yeah, should be epsiolon, and no not 2*epsilon, it should be + epsilon only, I maintain 3 vectors, policy wherr one variable is changed, old_policy where nothing is updated and new_policy which stores the next policy values.

Regarding convergence, we should be able to reduce the number of steps required for convergence by redcing the no of actions per agent. I feel if our agent is deterministic, it shouldn't matter if we run 100 actions on it or 1000 actions to find the value. This is not tested yet.

**Comment by AbdealiLoKo** [comment]
I find that the left,right method of gradient descent is bad. It's better to find the value of the policy and find the gradient by comparing that with value of +epsilon.

If I have N params, left,right method needs 2N episodes to find the gradient, while what I described above needs only N+1

**Comment by kunalgrover05** [comment]
I thought left right method gives a more accurate gradient, Since here we
are seeing how policy varies with one parameter increased and decreased
keeping the other params as constant, which should reflect on how a single
parameter causes changes. In this policy class it shouldn't matter, but for
more complex classes, it might matter.

http://about.me/kunalgrover05

_Kunal Grover_
about.me/kunalgrover05

http://about.me/kunalgrover05 http://about.me/kunalgrover05
http://about.me/kunalgrover05

**Comment by AbdealiLoKo** [comment]
It shouldnt matter. I'll explain some time in person

**Pull request closed without merging**
